### PR TITLE
Remove false positive warning

### PR DESCRIPTION
**Pull request by mernst**
Behavioral subtyping permits contravariant formal parameters:  the formal parameter of `m` in a subclass may be wider than the formal parameter of `m` in a superclass.  This pull request removes a mandated warning that unnecessarily forbids such contravariance.  Perhaps it would be better to turn this into an optional (checker-specific) warning, or to remove the method entirely in order that JSpecify does not take a stand.

### CODE REVIEW

**Comment by wmdietl** [comment]
This test case corresponds to issue #49 and, if I read the currect status correctly, at the moment we mandate this error.
So we shouldn't change this testcase without updating that issue and the documentation.

**Comment by mernst** [comment]
Thanks for linking the issue -- that is helpful.  I agree with you that this PR, the issue, and the documentation should be kept consistent.  Maybe this can prompt us to revisit that issue.

**Comment by cpovirk** [comment]
I see that you've posted on #49. Thanks. I have some thoughts that I'll put there, as well. (I see that is was actually reopened a while ago.)

If we want, we have some flexibility about what to do here even before that's settled.

On the one hand, the samples README describes `jspecify_nullness_mismatch` as applying in cases in which applying the normal JLS rules to nullness types would reject a piece of code. And it's true that normal JLS rules would reject an override with a different parameter type. So, even without officially writing a rule about this case one way or the other, we _theoretically_ already have an answer: This sample is "correct."

But we need to step back and consider the real point, just as in #166: The purpose of the samples is to be useful to tool authors. If we want to tool authors to be able to permit contravariance in parameter types, then a sample that works against that is at best controversial, and we may be better served by removing it. Granted, that still takes us back to debate of what we _do_ want. But at least it's a potentially easier question: "Do we want to allow tools to support this?" rather than "Do we want to write a part of the spec specifically to cover this?"

Again, though, for the actual heart of the debate, I'll post on #49.

**Comment by kevinb9n** [comment]
Not actionable while #49 is undecided, and will be the obvious consequence if #49 _is_ decided in this direction, so this PR has no current purpose; closing to avoid "PR blindness".

**Pull request closed without merging**
