### PR TITLE
Rename Facebook -> Meta

### PR DESCRIPTION
**Pull request by artempyanykh**
[What a time](https://about.facebook.com/meta)!

image

The domain is still the same though.

### CODE REVIEW

**Comment by artempyanykh** [comment]
Hm, I thought I've already signed a CLA quite a while ago. Anyway, will look into it sometime next week.

**Comment by cpovirk** [comment]
:(

I don't see a CLA associated with your GitHub username, nor with arr@fb.com. I can check other email addresses if it helps.

I have also avoided looking at the content of the pull request, so I can probably take a reasonable guess at what it looks like and send it to you for review if that's easier. Of course, we'd like you to be able to commit changes in the future, like for the spec, but you can decide when you want to tackle that and when you'd like the Meta rename done.

**Comment by artempyanykh** [comment]
Thanks @cpovirk and no worries :) I'll sign the CLA, just need dig up a couple emails first to double check that I indeed had a green light from legal.

**Comment by artempyanykh** [comment]
Apparently, the CLA check issues are due to my previous request being for `google/codeanalysis-annotations` repo. I've submitted a new approval request which hopefully won't take much time.

**Comment by artempyanykh** [comment]
The request went thru and supposedly the CLA should no longer be a problem. I'm going to re-create the PR.

**Pull request closed without merging**
