### PR TITLE
Change Pivotal to VMware on the website

### PR DESCRIPTION
**Pull request by sdeleuze**

### CODE REVIEW

**Review by KengoTODA — APPROVED** [review]
Change itself is LGTM. Not sure about the CLA issue.

**Comment by cpovirk** [comment]
It looks like the email address associated with the commit is sdeleuze@users.noreply.github.com. The CLA bot might want for the commit to be associated with a "real" address, but I'm not sure.

Then again, the CLA bot also doesn't have a signed CLA on file for your vmware.com address. I don't know if it has a CLA on file for another address of yours. Depending on who owns this code (you or VMware), you'll have to figure out which CLA applies in your case.

Alternatively, I can pretty well guess at what this PR does, and I can make the change myself. But if you'd like to be able to contribute more smoothly in the future, you may still want to look into the CLA. Let me know.

**Comment by sdeleuze** [comment]
@cpovirk Please do the changes yourself if possible, I will go through the process of getting the CLA approved by my employer for upcoming contributions.

**Comment by cpovirk** [comment]
Thanks for looking into that.

I pushed a change that probably does the right thing. Let me know if I should change anything else.

**Pull request closed without merging**
