### PR TITLE
Merge from main branch.

### PR DESCRIPTION
**Pull request by cpovirk**
```
git checkout samples-google-prototype
git merge main
gh pr create -a netdpb -B samples-google-prototype -t 'Merge from main branch.'
```

### CODE REVIEW

**Comment by cpovirk** [comment]
Eh, I should really have created a branch with a different name for this. Oh, well. Hopefully it still works.

(If only I'd tried to push to jspecify/jspecify instead of cpovirk/jspecify, I... well, either it would have stopped me and gotten me to create a branch with a new name, or I would have accidentally modified the branch directly instead of creating a PR :))

**Comment by cpovirk** [comment]
I've reenabled "Create a merge commit" / "Allow merge commits" in https://github.com/jspecify/jspecify/settings, and there is a >50% chance that I will remember to push that button when I am ready to merge. Then there is a >50% chance that that will do what we want.

**Comment by cpovirk** [comment]
And @netdpb just reminded me to do samples-google-prototype-eisop once we get this one working.

Also, I'll then want to turn support for merge commits back off....

**Review by netdpb — APPROVED** [review]

**Comment by cpovirk** [comment]
This resulted in some kind of weird extra layer of merges (as seen in https://github.com/jspecify/jspecify/commits/f5c3e61a2b4ee0b1b7611db452df8d70616b9252), but it seems to have fundamentally worked: If I run `git merge main` from `samples-google-prototype`, I get "Already up to date."

Or at least, if anything is going to go wrong, it won't go wrong until I try samples-google-prototype-eisop :) Here goes....

**Pull request merged**
