### PR TITLE
Try to fix javadoc link from site

### PR DESCRIPTION
**Pull request by kevinb9n**
probably needs to be an absolute link

### CODE REVIEW

**Comment by kevinb9n** [comment]
(I hope we are willing to let small .gitignore tweaks ride along with real changes)

**Comment by netdpb** [comment]
I think the problem was just a caching one. If I refresh the 404 page I get the Javadoc.

**Comment by netdpb** [comment]
Also, your URL redirects to https://jspecify.dev/docs/api/org/jspecify/nullness/package-summary.html.

**Comment by kevinb9n** [comment]
> I think the problem was just a caching one. If I refresh the 404 page I get the Javadoc.

Same here, but if I go back and do it again, I get the 404 again. I think it's because the javascript updates the browser to believe it's at that URL without actually loading that URL, which is what it would want to do for "internal" pages. Except it's weird that it even follows the redirect, then.

> Also, your URL redirects to https://jspecify.dev/docs/api/org/jspecify/nullness/package-summary.html.

Correct. See #267

**Comment by kevinb9n** [comment]
Since this *ought* to fix a broken link I think I'll submit it and handle any ongoing concerns in another PR if you have them.

**Pull request merged**
