### PR TITLE
Replace leading `@` in code snippets in Javadoc

### PR DESCRIPTION
**Pull request by netdpb**
Use `&commat;` so that the Javadoc processor doesn't try to interpret them as block tags.

### CODE REVIEW

**Comment by netdpb** [comment]
We could use `&64;` instead.

**Comment by cpovirk** [comment]
> That was discussed more somewhere else, possibly somewhere in #269.

OK, that actually wasn't as hard to find as I feared it would be:
https://github.com/jspecify/jspecify/pull/269#issuecomment-1223096045

**Comment by kevinb9n** [comment]
If there IS a fix that only requires ~6 little hacks like this and completely works I'd be okay with merging it.

**Comment by netdpb** [comment]
Closed as unnecessary after #290.

**Pull request closed without merging**
