### PR TITLE
Update documentation for 1.0.0

### PR DESCRIPTION
**Pull request by netdpb**
Please do not make any changes to this branch except via pull request onto the branch.

### CODE REVIEW

**Review by cpovirk — APPROVED** [review]
You could tweak the first line of that final PR description to reflect that it's a collection of miscellaneous fixes, since currently the first line describes only the first commit. But it's also fine not to bother.

**Comment by netdpb** [comment]
> You could tweak the first line of that final PR description to reflect that it's a collection of miscellaneous fixes, since currently the first line describes only the first commit. But it's also fine not to bother.

I think I did it?

**Comment by cpovirk** [comment]
GitHub shows a push just after it shows my comment, so we must have noticed simultaneously :) LGTM.

**Comment by cpovirk** [comment]
Oh, I misread. Yes, I think that did it.

**Pull request merged**
